nginx-acme:
  build: ./
  ports:
    - 80:80
    - 443:443
  environment:
    # Redirect letsencrypt.steveltn.me to https:://letsencrypt.org
    # NGINX_ACME_LETSENCRYPT.STEVELTN.ME to any value to enable
    - "NGINX_ACME_LETSENCRYPT.STEVELTN.ME=true"
