nginx-acme:
  build: ./
  ports:
    - 80:80
    - 443:443
  environment:
    # Redirect my.example.com to https:://letsencrypt.org
    # The value of the variable will be available as <%= domain.target %> in Nginx config
    - "NGINX-ACME_MY.EXAMPLE.COM=https://letsencrypt.org"
