nginx-acme:
  image: steveltn/nginx-acme
  ports:
    - 80:80
    - 443:443
  links:
    - wordpress
  environment:
    # Forward wordpress.steveltn.me to the WordPress container
    - "FORWARD_WORDPRESS.STEVELTN.ME=http://wordpress"

wordpress:
  image: wordpress
  links:
    - db:mysql

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
