nginx-acme:
  image: steveltn/nginx-acme
  ports:
    - 80:80
    - 443:443
  links:
    - wordpress
  environment:
    # Forward wordpress.example.com to the WordPress container
    - "NGINX-ACME_WORDPRESS.EXAMPLE.COM=http://wordpress"

    # Using staging server by default, for there is a rate limit on production
    # Uncomment to use Let's Encrypt production server
    # - "PRODUCTION=true"

wordpress:
  image: wordpress
  links:
    - db:mysql

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: gohJoom2quai8hac
