https-portal:
  build: ../../..
  ports:
    - 80:80
    - 443:443
  links:
    - wordpress
  environment:
    DOMAINS: $TEST_DOMAIN->http://wordpress
    FORCE_RENEW: $FORCE_RENEW

wordpress:
  image: wordpress
  links:
    - db:mysql

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: gohJoom2quai8hac
